import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [listXY, setListXY] : any = useState([]);

  const handler = (event:any) => {

    const newDot : any = {
      clientX: event.clientX,
      clientY: event.clientY
    };

    console.log(newDot);
    setListXY((prev: any) => [...prev, newDot]);

  }

  const handleDo = (event:any) => {
    event.stopPropagation();
    console.log("Do");
  }

  
  const handleUnDo = (event:any) => {
    event.stopPropagation();
    console.log("Undo");

    setListXY((prev:any) => {
      const newArray = [...prev].splice(0, -1);
      return newArray;
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page} onClick={handler} >
        <button className={styles.buttons} onClick={handleDo}>Do</button>
        <button className={styles.buttons} onClick={handleUnDo}>Undo</button>
        {listXY.map((item:any) => ( 
          <div
            key={1}
            className={ styles.dot } 
            style={{ left: item.clientX, top: item.clientY }}
          />  
        ))}
      </div>
    </>
  )
}
