import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [listXY, setListXY] = useState([]);

  const handler = (event:any) => {

    const newDot = {
      clientX: event.clientX,
      clientY: event.clientY
    };

    console.log(newDot);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page} onClick={handler} >
        <div className={styles.dot}></div>
      </div>
    </>
  )
}
